---
title: "Midwestern Presidential Votes Explorer"
author: "Jason Heppler"
date: "1/30/2017"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, echo = FALSE, warning = FALSE, error = FALSE, message = FALSE}
library(leaflet)
library(tidyr)
library(scales)
library(tigris)
library(dplyr)
library(htmlwidgets)
library(readr)

###--------------------------------------------------
### Merge census county-level dataset with map data
###--------------------------------------------------

# Read in data and join to shapefile
datafile <- "data/2016_US_County_Level_Presidential_Results.csv"
flippedCounties <- "data/US_County_Level_Presidential_Results_08-16.csv"
election <- read_csv(datafile)
flipped <- read_csv(flippedCounties)

# Subset county shapefiles to midwestern states and 
# generate a combined FIPS to match against 
# the datafile FIPS.
shp_data <- counties(state = c("MN","SD", "ND", "NE", "WI", "IA", "IL", "OH", "MI", "IN", "MO", "KS"), cb = TRUE, resolution = "20m")
shp_data@data <- shp_data@data %>%
                    mutate(combined_fips = paste(STATEFP, COUNTYFP, sep=""))

# Merge data
library(raster)
midwestMap <-  merge(shp_data, election, by.x = "combined_fips", by.y = "combined_fips")
midwestFlippedData <- merge(midwestMap, flipped, by.x = "combined_fips", by.y = "fips_code")

###--------------------------------------------------
### Data analysis and statistics
###--------------------------------------------------

# Determine which counties flipped in the 2016 election
## 1 = dem flip
## 2 = gop flip
## 3 = incumbent
midwestFlippedData@data$flipped_counties <- 
  ifelse(midwestFlippedData@data$dem_2016 > midwestFlippedData@data$gop_2016 &
        midwestFlippedData@data$dem_2008 < midwestFlippedData@data$gop_2008, 1,
        ifelse(midwestFlippedData@data$dem_2016 < midwestFlippedData@data$gop_2016 &
               midwestFlippedData@data$dem_2008 > midwestFlippedData@data$gop_2008, 2, 0))
        
# Find min and max percentages for the palette
minPct <- min(c(midwestMap@data$per_dem, midwestMap@data$per_gop))
maxPct <- max(c(midwestMap@data$per_dem, midwestMap@data$per_gop))

###--------------------------------------------------
### Make maps
###--------------------------------------------------

midwestPalette <- colorBin(palette = "Blues", domain = c(minPct, maxPct), bins = c(0, .3, .4, .5, .6, .7, .8, .9, 1), pretty = FALSE)
midwestFlippedPalette <- colorBin(palette = "RdBu", domain = c(0, 2), bins = 3, pretty = FALSE)

midwestPopup <- paste0("<b>", "County: ", "</b>", midwestMap@data$county_name, "<br>",
                       "<b>", "GOP votes (2016): ", "</b>", midwestMap@data$votes_gop, "<br>",
                       "<b>", "Dem votes (2016): ", "</b>", midwestMap@data$votes_dem, "<br>",
                       "<b>", "Difference (2016): ", "</b>", midwestMap@data$diff, "<br>")

baseMap <- "https://api.mapbox.com/styles/v1/hepplerj/cih5dktre003ba0m3p7raqa7p/tiles/256/{z}/{x}/{y}@2x?access_token=pk.eyJ1IjoiaGVwcGxlcmoiLCJhIjoiMjNqTEVBNCJ9.pGqKqkUDlcFmKMPeoARwkg"
mbAttribution <- "© <a href='https://www.mapbox.com/map-feedback/'>Mapbox</a> © <a href='http://www.openstreetmap.org/copyright'>OpenStreetMap</a>"

# County level votes
midwestResults <- leaflet(shp_data) %>%
  addTiles(urlTemplate = baseMap, attribution = mbAttribution) %>%
  addPolygons(stroke = TRUE,
              smoothFactor = 0.2,
              weight = 1,
              fillOpacity = 0.6,
              color = ~midwestPalette(midwestMap@data$per_dem),
              popup = midwestPopup,
              group = "Democratic Vote"
             ) %>%
  addPolygons(stroke = TRUE,
              smoothFactor = 0.2,
              weight = 1,
              fillOpacity = 0.6,
              color = ~midwestPalette(midwestMap@data$per_gop),
              popup = midwestPopup,
              group = "Republican Vote"
              ) %>%
  addLegend("bottomright", pal = midwestPalette, values = ~midwestMap@data$per_dem, title = "Results",
             labFormat = labelFormat(suffix = '%', between = '% - ',
                                     transform = function(x) 100 * x)
           ) %>%
  addLayersControl(
    baseGroups=c("Democratic Vote", "Republican Vote"),
    position = "bottomleft",
    options = layersControlOptions(collapsed = FALSE)
  )

# Results
midwestResults
```

## Dumbbell Charts

```{r echo = FALSE, warning = FALSE, error = FALSE, message = FALSE} 
library(ggplot2)
library(ggalt)
library(bsselectR)

election$county_name_clean <- gsub("County", "", election$county_name)

states <- as.character(sort(unique(election$state_abbr)))
states <- states[!is.na(states)]

plots <- lapply(states, function(x) {
  
  state = filter(election, state_abbr == x)
  
  p <- ggplot()
  p <- p + geom_dumbbell(data=state,
                        aes(x = per_dem, xend = per_gop,
                            y = county_name_clean),
                        color="#b2b2b2",
                        size = 0.3,
                        point.colour.l = "#0e668b",
                        point.colour.r = "#8b100e") +
  labs(x = NULL, y = NULL) +
  theme_bw() +
  theme(axis.title = element_text(family = "Lato Black", color="#666666", face="bold", size=6)) +
  theme(plot.background=element_rect(fill="#f7f7f7")) +
  theme(panel.background=element_rect(fill="#f7f7f7")) +
  theme(panel.grid.minor=element_blank()) +
  theme(panel.grid.major.y=element_blank()) +
  theme(panel.grid.major.x=element_line()) +
  geom_vline(xintercept = .50) +
  geom_vline(xintercept = .20, linetype="dotted", colour="lightgray") +
  geom_vline(xintercept = .40, linetype="dotted", colour="lightgray") +
  geom_vline(xintercept = .60, linetype="dotted", colour="lightgray") +
  geom_vline(xintercept = .80, linetype="dotted", colour="lightgray") +
  theme(axis.ticks=element_blank()) +
  theme(plot.title=element_text(face="bold", family="Lato Regular", size=14)) +
  theme(plot.subtitle=element_text(family="Lato Regular", size=12)) +
  theme(plot.caption=element_text(family="Lato Regular", size=10, color="gray", margin=margin(t=10, r=80))) +
  labs(title = paste("Support for Clinton and Trump, ", state$state_abbr),
                subtitle = "Percentage of votes for Clinton and Trump in 2016",
                caption="Jason A. Heppler <jason@jasonheppler.org>") +
  theme(panel.border=element_blank()) +
  theme(axis.text.y = element_text(family="Lato Regular", size=5)) +
  theme(legend.position="none")
  
  p
  
})

library(tidyverse)
paths <- paste0(states, ".png")
pwalk(list(paths, plots), ggsave, path = "plots", dpi = 300)

# Dropdown

library(stringr)
library(bsselectR)

state_plots <- paste0(list.files("plots", full.names = TRUE))
names(state_plots) <- str_replace_all(state_plots,
                                      c("\\.png" = '',
                                      "plots/" = ''))
bsselect(state_plots, type = "img", selected = "NE",
         live_search = TRUE, show_tick = TRUE)
```